# ============================================================
# APPLICATION PROPERTIES
# Think of this as your app's configuration/settings file.
# Spring Boot reads this on startup.
# ============================================================

# --- App Name ---
spring.application.name=core-payment-system

# --- Server Port ---
# Your app will run at: http://localhost:8080
server.port=8080

# ============================================================
# DATABASE CONFIGURATION
# Change these values to match YOUR MySQL setup.
# Make sure you create the database first:
#   CREATE DATABASE payment_db;
# ==============================================================
# ============================================================
# H2 IN-MEMORY DATABASE (Temporary for testing)
# ============================================================
spring.datasource.url=jdbc:h2:mem:payment_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

logging.level.org.springframework.web.servlet.resource=OFF
# ============================================================
# JPA / HIBERNATE SETTINGS
# JPA = Java Persistence API (how Java talks to databases)
# Hibernate = the implementation of JPA Spring Boot uses
# ============================================================



# ============================================================
# LOGGING
# ============================================================
# Show DEBUG logs for our own package only
logging.level.com.payments=DEBUG

# Show what SQL parameters are being used
logging.level.org.hibernate.type.descriptor.sql=TRACE
