package com.payments.core.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * ============================================================
 * PAYMENT ENTITY (Model Layer)
 * ============================================================
 * This Java class maps directly to the 'payments' table in MySQL.
 *
 * KEY ANNOTATIONS EXPLAINED:
 *
 * @Entity       → Tells JPA/Hibernate: "This class is a database table"
 * @Table        → Specifies the exact table name in MySQL
 * @Id           → Marks the primary key field
 * @GeneratedValue → Auto-increments the ID (MySQL does this for us)
 * @Column       → Maps a field to a specific column (with constraints)
 *
 * LOMBOK ANNOTATIONS (removes boilerplate code):
 * @Data         → Auto-generates: getters, setters, toString, equals, hashCode
 * @Builder      → Lets you build objects like: Payment.builder().amount(...).build()
 * @NoArgsConstructor → Generates empty constructor: new Payment()
 * @AllArgsConstructor → Generates constructor with all fields
 * ============================================================
 */
@Entity
@Table(name = "payments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

    /**
     * Primary Key — auto-incremented by MySQL.
     * Example: 1, 2, 3, 4 ...
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Our unique identifier for each payment.
     * We generate this ourselves using UUID.
     * unique = true → MySQL enforces no duplicate transaction IDs.
     * nullable = false → This field MUST have a value.
     */
    @Column(name = "transaction_id", unique = true, nullable = false)
    private String transactionId;

    /**
     * The merchant who initiated the payment.
     * Example: "MERCHANT_001"
     */
    @Column(name = "merchant_id", nullable = false)
    private String merchantId;

    /**
     * The merchant's own order reference.
     * Example: "ORDER_12345"
     */
    @Column(name = "order_id", nullable = false)
    private String orderId;

    /**
     * Payment amount. We use BigDecimal for money — never use float/double for money!
     * precision=10 → max 10 digits total
     * scale=2 → max 2 decimal places (e.g., 1234.56)
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    /**
     * Currency code like "INR", "USD", "EUR"
     */
    @Column(nullable = false, length = 3)
    private String currency;

    /**
     * Current status of the payment.
     * We use an Enum stored as a String in the database.
     * @Enumerated(EnumType.STRING) → stores "PENDING", not 0, 1, 2
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private PaymentStatus status = PaymentStatus.PENDING;

    /**
     * URL the payment gateway will call when payment is done.
     * Example: "https://merchant.com/payment/callback"
     */
    @Column(name = "callback_url")
    private String callbackUrl;

    /**
     * The checkout URL generated by the (mock) payment gateway.
     * Merchant redirects user here to complete payment.
     */
    @Column(name = "payment_url")
    private String paymentUrl;

    /**
     * Signature used to verify callbacks are genuinely from our gateway.
     * This prevents fake/malicious callbacks.
     */
    @Column(name = "gateway_signature")
    private String gatewaySignature;

    /**
     * Timestamp when this record was first created.
     * @CreationTimestamp → Hibernate sets this automatically on INSERT.
     * updatable = false → This value never changes after creation.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last update.
     * @UpdateTimestamp → Hibernate updates this automatically on every UPDATE.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;


    // ============================================================
    // INNER ENUM: PaymentStatus
    // An Enum is a special class with a fixed set of constants.
    // Using an Enum prevents typos like "SUCCES" or "sucess".
    // ============================================================
    public enum PaymentStatus {
        PENDING,   // Payment initiated but not yet completed
        SUCCESS,   // Payment confirmed by gateway
        FAILED     // Payment failed or was declined
    }
}
